title: Random Tech Stuff
author: Davide Guerri
description: Hi. This is my blog with random technical (and sometimes non-technical) stuff.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
