title: Random Tech Stuff
author: Davide Guerri
description: Hi. This is my blog with random technical (and sometimes non-technical) stuff.

twitter:
  username: dguerri

baseurl: "/random-tech-stuff"
url: "https://dguerri.github.io"

fbcomments:
  appid: 886478268951212
  nonce: hE0UtsU3

new_google_analytics: G-M9Z323FVQ2

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-target-blank
  - jekyll-redirect-from
  - jekyll-seo-tag

target-blank:
  rel: nofollow

header_page_refs: ["about", "contact"]

cayman-blog:
  date_format: "%Y-%m-%d"

whitelist:
  - jekyll-redirect-from
